config/routes.rb
Rails.application.routes.draw do
  
  # VERB          # PATH          # CONTROLLER#METHOD
  # Routes de Menu  
  root to: 'menu#index'
  get         '/menu/cerveja-por-temperatura',                  to: "menu#form_for_beer_by_temperature"
  post        '/menu/cerveja-por-temperatura',                  to: "menu#form_for_beer_by_temperature"
  post        '/menu/resultado/cerveja-por-temperatura',        to: "menu#result_of_beer_by_temperature"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController

  def index

  end

  def form_for_beer_by_temperature

  end

  def result_of_beer_by_temperature
    @given_temperature = beer_by_temperature_params.to_i
    @best_beer = MenuService.new(@given_temperature).calculates_best_beer_by_temperature
  end

  private
    def beer_by_temperature_params
      params[:temperature]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeermachineApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <span class="navbar-brand">Boa Breja APP</span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Início", root_path, :class => "btn btn-light" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown">
              <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Escolher cerveja
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to "Por temperatura", menu_cerveja_por_temperatura_path, :class => "dropdown-item" %>
                <%= link_to "Por região", "#", :class => "dropdown-item" %>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <br>
      <%= yield %>
    </div>
  </body>
</html>

app/views/menu/form_for_beer_by_temperature.html.erb
<div class="card" style="width: 36rem;">
  <div class="card-body">
    <h5 class="card-title">Melhor cerveja por temperatura</h5>
    <h6 class="card-subtitle mb-2 text-muted">Encontre a melhor cerveja para a sua temperatura preferida</h6>

    <%= form_with(url: menu_resultado_cerveja_por_temperatura_path, method: 'post', local: true) do |form| %>
      <div class="form-group">
        <div class="input-group mb-2">
          <div class="input-group-prepend">
            <div class="input-group-text">Temperatura em °C:</div>
          </div>
          <%= text_field_tag :temperature, nil, placeholder: 'Ex.: -2', class: 'form-control' %>
        </div>
      </div>
      <%= button_tag 'Calcular', class: 'btn btn-success' %>
    <% end %>

  </div>
</div>

app/views/menu/index.html.erb
<div class="card" style="width: 36rem;">
  <div class="card-body">
    <h5 class="card-title">Melhor cerveja por temperatura</h5>
    <h6 class="card-subtitle mb-2 text-muted">Encontre a melhor cerveja para a sua temperatura preferida</h6>
    <p class="card-text">Nos diga a sua temperatura preferida e nós calcularemos qual é a melhor
      cerveja para você.
    </p>
    <%= button_to "Desce uma!", menu_cerveja_por_temperatura_path,:class => "btn btn-success" %>
  </div>
</div>

app/views/menu/result_of_beer_by_temperature.html.erb
<div class="card" style="width: 36rem;">
  <div class="card-body">
    <h5 class="card-title">A melhor cerveja para a temperatura <%= @given_temperature %>°C é:</h5>
    <br>
    <h3 class="card-title">
      <%= @best_beer %>
    </h3>
    <br>
    <%= button_to "< Calcular novamente", menu_cerveja_por_temperatura_path,:class => "btn btn-info" %>
  </div>
</div>